name: swarm-id
region: fra

# Domain configuration
domains:
  - domain: swarm-id.snaha.net
    type: PRIMARY

# Static site for swarm-id.snaha.net
# Serves SvelteKit identity management UI plus proxy/auth pages
static_sites:
  - name: id-app
    # GitHub auto-deploy configuration
    github:
      repo: snaha/swarm-id-explorations
      branch: feat/create-swarm-ui
      deploy_on_push: true

    source_dir: /
    output_dir: swarm-id-build

    # Build using monorepo scripts
    build_command: git submodule update --init --recursive && npm install -g pnpm && pnpm install && pnpm build:swarm-id

    # SPA routing - all routes go to index.html except /demo
    catchall_document: index.html

    # CORS headers for cross-origin communication with swarm-demo
    cors:
      allow_origins:
        - exact: https://swarm-demo.snaha.net
      allow_methods:
        - GET
        - POST
        - OPTIONS
      allow_headers:
        - Content-Type
      allow_credentials: true
      max_age: "600s"

# Environment variables
envs:
  - key: NODE_ENV
    value: production

  - key: ORIGIN
    value: https://swarm-id.snaha.net

  - key: APP_DOMAIN
    value: https://swarm-demo.snaha.net

  - key: ID_DOMAIN
    value: https://swarm-id.snaha.net
