name: swarm-demo
region: fra

# Static site for swarm-demo.snaha.net
# Serves demo pages with bundled library
static_sites:
  - name: demo-app
    # GitHub auto-deploy configuration
    github:
      repo: snaha/swarm-id-explorations
      branch: feat/create-swarm-ui
      deploy_on_push: true

    source_dir: /
    output_dir: demo/build

    # Build using monorepo scripts
    build_command: pnpm install && pnpm build:swarm-demo

    # Serve as SPA with index.html fallback
    catchall_document: index.html

    # CORS headers for cross-origin communication with swarm-id
    cors:
      allow_origins:
        - exact: https://swarm-id.snaha.net
      allow_methods:
        - GET
        - POST
        - OPTIONS
      allow_headers:
        - Content-Type
      allow_credentials: true
      max_age: 600

# Environment variables
envs:
  - key: NODE_ENV
    value: production

  - key: APP_DOMAIN
    value: https://swarm-demo.snaha.net

  - key: ID_DOMAIN
    value: https://swarm-id.snaha.net
